# This is a basic workflow to help you get started with Actions
name: deploy the concis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Build
        run: yarn && yarn docs:build

      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CONCIS_SSH_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'docs-dist'
          REMOTE_HOST: ${{ secrets.CONCIS_HOST }}
          REMOTE_USER: ${{ secrets.CONCIS_USERNAME }}
          TARGET: '/www/wwwroot/concis-docs'
