name: pr_check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install
        run: yarn

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: jest test
        run: yarn test:jest
